cost function:
  cost type: $(cost_function)
  window begin: '{{window_begin}}'
  window length: $(window_length)
  geometry:
    $(GEOMETRY)
  model:
    $(MODEL)
  analysis variables: $(an_variables)
  background:
    $(BACKGROUND)
  background error:
    $(BACKGROUND_ERROR)
  observations:
    $(OBSERVATIONS)
  variable change: Ana2Model #Identity
  rotate:
    u: [uocn]
    v: [vocn]

variational:
  minimizer:
    algorithm: RPCG
  iterations:
  - ninner: $(ninner)
    gradient norm reduction: $(reduc)
    geometry:
      $(GEOMETRY)
    linear model:
      $(LINEAR_MODEL)
    diagnostics:
      departures: ombg
    online diagnostics:
      write increment: true
    increment:
      datadir: "."
      date: '{{current_cycle}}'
      exp: $(experiment)
      type: incr

final:
  diagnostics:
    departures: oman

output:
  $(AN_OUTPUT)